import { Theme } from '@radix-ui/themes';
import './globals.css'
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextAuthSessionProvider from '@/providers/sessionProvider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <NextAuthSessionProvider>
          <Theme accentColor="mint" radius="small" appearance='dark' suppressHydrationWarning>
            {children}
          </Theme>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
